name: Java CI for SC2002 Lab1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit 5 Console Standalone
      run: |
        curl -LO https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar

    - name: Compile source files
      run: |
        mkdir out
        javac -d out -cp junit-platform-console-standalone-1.10.2.jar lab1/*.java tests/*.java

    - name: Run JUnit tests
      run: |
        java -jar junit-platform-console-standalone-1.10.2.jar \
          --class-path out \
          --scan-class-path \
          --include-classname=.*Tests
